Backup/T034/Controllers/AdminController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Db.DataAccess;
using Db.Entity;
using Db.Entity.Directory;
using T034.Models;
using T034.Tools.FileUpload;

namespace T034.Controllers
{
    public class AdminController : Controller
    {
        private readonly IBaseDb _db;

        public AdminController()
        {
            _db = MvcApplication.DbFactory.CreateBaseDb();
        }

        public ActionResult GoodsList()
        {
            var items = _db.Select<Goods>();
            return View(items);
        }

        [HttpGet]
        //[AuthorizeUser]
        public ActionResult AddGoods()
        {
            return View();
        }

        [HttpGet]
        //[AuthorizeUser]
        public ActionResult AddGoodsDetail(int goodsId)
        {
            return View(new GoodsDetail { Goods = new Goods { Id = goodsId } });
        }

        /// <summary>
        /// PurposeList = SelectListItems<Purpose>(), TechnologyList = SelectListItems<Technology>()
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        private IEnumerable<SelectListItem> SelectListItems<T>() where T : DirectoryEntity
        {
            var purposes = _db.Select<T>().Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });
            return purposes;
        }

        public ActionResult AddGoods(Goods item)
        {
            var result = _db.Save(item);

            return RedirectToAction("Goods", new {id = result});
        }

        public ActionResult AddGoodsDetail(GoodsDetail item)
        {
            var result = _db.Save(item);

            return RedirectToAction("Goods", new { id = item.Goods.Id });
        }


        public ActionResult Goods(int id)
        {
            var item = _db.Get<Goods>(id);
            return View(item);
        }

        [HttpPost]
        public ActionResult UploadFile()
        {
            var path = Path.Combine(Server.MapPath("~/Files"));
            var model = FileUploadModel.ParseParam(Request.Files.Keys[0]);
            path = Path.Combine(path, model.Category, model.Id);
            var uploader = new Uploader(path);

            var r = new List<ViewDataUploadFilesResult>();
            if (Request.Files.Cast<string>().Any())
            {
                var statuses = new List<ViewDataUploadFilesResult>();
                var headers = Request.Headers;
                if (string.IsNullOrEmpty(headers["X-File-Name"]))
                {
                    uploader.UploadWholeFile(Request, statuses);
                }
                else
                {
                    uploader.UploadPartialFile(headers["X-File-Name"], Request, statuses);
                }
                JsonResult result = Json(statuses);
                result.ContentType = "text/plain";
                return result;
            }
            return Json(r);
        }
    }
}

Backup/T034/Controllers/AuthController.cs
using System.Web;
using System.Web.Mvc;
using T034.Tools.Auth;

namespace T034.Controllers
{
    public class AuthController : Controller
    {
        /// <summary>
        /// Сюда приходит после авторизации на яндексе
        /// </summary>
        /// <returns></returns>
        public ActionResult LoginWithYandex()
        {
            var model = YandexAuth.GetToken(Request);

            var userCookie = YandexAuth.TokenCookie(model);
            Response.Cookies.Set(userCookie);

            return RedirectToActionPermanent("Index", "Home");
        }

        /// <summary>
        /// Сюда приходит после авторизации на Mail
        /// </summary>
        /// <returns></returns>
        public ActionResult LoginWithMail()
        {
            var model = MailAuth.GetToken(Request);

            var userCookie = MailAuth.TokenCookie(model);
            Response.Cookies.Set(userCookie);

            return RedirectToActionPermanent("Index", "Home");
        }

        public ActionResult Logout()
        {
            HttpCookie aCookie;
            string cookieName;
            int limit = Request.Cookies.Count;

            for (int i = 0; i < limit; i++)
            {
                cookieName = Request.Cookies[i].Name;
                aCookie = new HttpCookie(cookieName);
                aCookie.Value = "";
                Response.Cookies.Set(aCookie);
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult RedirectToYandex()
        {
            return Redirect(string.Format("https://oauth.yandex.ru/authorize?response_type=code&client_id={0}", YandexAuth.ClientId));
        }

        public ActionResult RedirectToMail()
        {
            return Redirect(string.Format("https://connect.mail.ru/oauth/authorize?client_id={0}&response_type=code&redirect_uri={1}", MailAuth.SiteId, MailAuth.RedirectUri));
        }
    }
}

Backup/T034/Views/Shared/AdminMenu.cshtml
<ul class="nav nav-tabs">
    <li>@Html.ActionLink("Товары", "GoodsList", "Admin")</li>
</ul>

Backup/T034/Views/Shared/AuthPartialView.cshtml
@model T034.Models.UserModel

@Model.Name 

@if (Model.IsAutharization)
{
    @Html.ActionLink("Выйти", "Logout", "Auth")
}
else
{
    <a href="@Url.Action("RedirectToYandex", "Auth")"><img src="/Content/images/yandex_icon.png" height="25px" width="25px" alt="Войти при помощи Яндекса"/> </a>
    <a href="@Url.Action("RedirectToMail", "Auth")"><img src="/Content/images/yandex_icon.png" height="25px" width="25px" alt="Войти при помощи Mail.ru"/> </a>
}
@using (Html.BeginForm("RedirectToYandex", "Auth"))
{
    @Html.Hidden("token")
}

Backup/T034/Views/Shared/FileUploadPartialView.cshtml
@model T034.Models.FileUploadModel
<link href="@Url.Content("~/Content/jQuery.FileUpload/css/jquery.fileupload.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/jQuery.FileUpload/css/jquery.fileupload-ui.css")" rel="stylesheet" type="text/css" />
<!-- The fileinput-button span is used to style the file input field as button -->
<span class="btn btn-success fileinput-button">
    <i class="glyphicon glyphicon-plus"></i>
    <span>Выбрать файлы</span>
    <!-- The file input field used as target for the file upload widget -->
    <input id="fileupload" type="file" name="files[]" multiple>
</span>
<br>
<br>
<!-- The global progress bar -->
<div id="progress" class="progress">
    <div class="progress-bar progress-bar-success"></div>
</div>
<!-- The container for the uploaded files -->
<div id="files" class="files"></div>

<!-- The basic File Upload plugin -->
<script src="@Url.Content("~/Scripts/jQuery.FileUpload/jquery.fileupload.js")" type="text/javascript"></script>
<script>
    /*jslint unparam: true */
    /*global window, $ */
    $(function () {
        'use strict';
        // Change this to the location of your server-side upload handler:
        var url = '@Url.Content(@Model.Url)';
        $('#fileupload').fileupload({
            url: url,
            dataType: 'json',
            paramName: '@Model.ToString()',
            done: function (e, data) {
                $.each(data.result, function (index, file) {
                    $('<div class="alert alert-success" role="alert"/>').text(file.name).appendTo('#files');
                });
            },
            fail: function (e, data) {
                $.each(data.files, function (index, file) {
                    $('<div class="alert alert-danger" role="alert"/>').text(file.name + ' ошибка').appendTo('#files');
                });
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('#progress .progress-bar').css(
                'width',
                progress + '%'
            );
            }
        }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');
    });
</script>

Backup/T034/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/DataTables-1.10.2/media/css/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-1.9.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.9.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/DataTables-1.10.2/media/js/jquery.dataTables.min.js")" type="text/javascript"></script>
    
</head>

    <body>
        <div class="container">
        @{
            Html.RenderAction("Auth", "Home");
        }
            <ul class="nav nav-tabs">
                <li>@Html.ActionLink("3D объекты", "SubjectList", "Product")</li>
                <li>@Html.ActionLink("3D принтеры", "PrinterList", "Product")</li>
                <li>@Html.ActionLink("Пластик", "MaterialList", "Product")</li>
            </ul>
            @Html.Partial("AdminMenu")
        @RenderBody()
        </div>
    </body>
</html>

Backup/T034/Views/Shared/_SimpleLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/DataTables-1.10.2/media/css/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-1.9.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.9.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/DataTables-1.10.2/media/js/jquery.dataTables.min.js")" type="text/javascript"></script>
    
</head>

    <body>
        <div class="container">
            @RenderBody()
        </div>
    </body>
</html>